CREATE TABLE BIBLIOTECARIO (
	idBibliotecario INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE LIVROS(
	idLivros INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    autor VARCHAR(100),
    idBibliotecario INT NOT NULL,
    FOREIGN KEY (idBibliotecario) REFERENCES BIBLIOTECARIO(idBibliotecario)
);

CREATE TABLE ALUNO(
	idAluno INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    cpf CHAR(11) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    telefone CHAR(9)  NOT NULL UNIQUE
);

CREATE TABLE EMPRESTIMO(
	idEmprestimo INT PRIMARY KEY AUTO_INCREMENT,
    dataEmprestimo DATE NOT NULL,
    dataFimEmprestimo DATE NOT NULL,
    idAluno INT NOT NULL,
    idLivros INT NOT NULL,
    FOREIGN KEY (idAluno) REFERENCES ALUNO(idAluno),
    FOREIGN KEY (idLivros) REFERENCES LIVROS(idLivros)
)
