"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Moto_1 = require("./Moto");
var Carro_1 = require("./Carro");
var car = new Carro_1.Carro("Xiaomi", "SU7", 10);
var bike = new Moto_1.Moto("harley davidson", "FatBoy", 40);
car.acelerar();
car.acelerar();
car.acelerar();
car.freiar();
car.freiar();
car.freiar();
console.log("------------------------");
bike.acelerar();
bike.acelerar();
bike.acelerar();
bike.freiar();
bike.freiar();
bike.freiar();
